### ISSUE TITLE
Inconsistencies with setting tags

### ISSUE THREAD

**Issue by wtpisaac** [Slugbotics/SluggoAPI#40]
There seems to be inconsistency with PUTting or PATCHing the tag_list item on tickets. In my experience, it works semi-reliably for tag ID 2, but was not working with a blank list or tag ID 1.

Not sure if this can be reproduced or not. Would be good to investigate.

**Comment by tdimhcsleumas** [comment]
Blank list is fixed. I made the wrong assumptions about where the tag_list would be called when I wrote the business logic to remove tags. Still investigating why ID 1 causes problems.

**Comment by tdimhcsleumas** [comment]
It's fixed. Pushing
