### ISSUE TITLE
Feature Request: Implement server-sided authentication

### ISSUE THREAD

**Issue by tdimhcsleumas** [Slugbotics/SluggoAPI#74]
As a user, I want to ensure that my login isn't vulnerable to CRSF attacks. To fix this, utilize the CRSF features provided by Django and implement a server-side rendered authentication flow for account-related requirements. As an initial pass, this should leverage Django's `contrib.auth` module and create a minimally-styled login form that supports login and account creation. LOGIN_REDIRECT_URL's must also be added to `settings.py` in order to point back to the frontend (should this be an environment variable?). This pass should be implemented alongside the existing endpoints, in order to prevent issues with iOS clients.

Long term, removing authentication from the rest api altogether could be ideal, but best not to break things for now.

**Comment by agavgavi** [comment]
iOS clients could use server sided login as that's already common in other apps. For example xfinity and other oauth apps open a webpage in the app that you log into and then it provides tokens back to the app. No idea how it's done but it could be used.

**Comment by tdimhcsleumas** [comment]
Yeah, that's what I was thinking. I think we'd need to see how to extract token data returned from the web-client that pops up on iOS.
